[main]
font=Ioskeley Mono:size=12
prompt="󱘝  "
sort-result=no
width=40
lines=15
horizontal-pad=20
vertical-pad=10
inner-pad=5

# Center it on screen
anchor=center

[colors]
background=1b1b20ff 
text=ffffffff
match=818181ff
selection=292930ff
selection-text=ffffffff
# Adding a border color helps it pop against dark backgrounds
border=818181ff

[border]
width=2
radius=10
