#Local Variables

$fontFamily = DepartureMono Nerd Font
$fn_greet=echo "Good $(date +%H | awk '{if ($1 < 12) print "Morning"; else if ($1 < 18) print "Afternoon"; else print "Evening"}'), Comrade"
$textColor = rgb(fbf1c7)
$fieldColor = rgba(28282899)
$outerColor = rgb(d65d0e)
$checkColor = rgb(b8bb26)
$failColor = rgb(fb4934)

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/torii.png
    blur_size = 6
    blur_passes = 3
}

#TIME
label {
	monitor = 
	text = $TIME12
	color = $textColor
	font_size = 90
	font_family = $fontFamily Bold
	position = 0, 150 
	halign = center
	valign = center
}

#DATE
label {
	monitor = 
	text = cmd[update:43200000] date +"%A, %d %B %Y"
	color = $textColor
	font_size = 25
	font_family = $fontFamily Bold
	position = 0, 40
	halign = center
	valign = center
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $fieldColor

    outer_color = $outerColor
    check_color = $checkColor
    fail_color = $failColor

    font_color = $textColor
    fade_on_empty = false
    rounding = -1

    font_family = $fontFamily Bold
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    # uncomment if you wish to display a message during authentication
    check_text = checking...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 10%
    halign = center
    valign = bottom
}

# Greeting

label {
	monitor =
	text = cmd[update:60000] $fn_greet
	color = $textColor
	font_size = 32
	font_family = $fontFamily Bold
	position = 0, -16%
	halign = center
	valign = center
}
