general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 50
    on-timeout = loginctl lock-session
}

listener {
    timeout = 100
    on-timeout = wlopm --off '*'
    on-resume = wlopm --on '*'
}

# listener {
#     timeout = 200
#     on-timeout = systemctl suspend
# }
